services:
  # db:
  #   container_name: postgresLocal
  #   image: postgres
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_PASSWORD: 123456
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  nestjs-postgres-backend:
    container_name: nestjs-postgres-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
# volumes:
#   pgdata:
