name: Deploy NestJs App via FTP
on:
  push:
    branches:
      - main

jobs:
  build-deploy-and-trigger-start:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: setup nodejs app
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          echo ".env file created from secret"

      - name: Install dependency
        run: npm ci

      - name: Build App
        run: npm run build

      - name: ðŸ§¹ Clean up unnecessary files
        run: |
          rm -rf node_modules
          rm -rf src
          echo "Cleanup complete"

      - name: ðŸš€ Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /nestjs-backend/dist/
          local-dir: ./dist/
          port: 21
          protocol: ftps
          dangerous-clean-slate: false

      - name: ðŸšš Upload config files (.env + package.json)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /nestjs-backend/
          local-dir: ./
          include: |
            package.json
            package-lock.json
            .env
          dangerous-clean-slate: false

      - name: Prepare tmp directory with fresh restart.txt
        run: |
          mkdir -p tmp
          date > tmp/restart.txt

      - name: Restart trigger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /nestjs-backend/tmp/
          local-dir: ./tmp/
          port: 21
          protocol: ftps
          dangerous-clean-slate: false
